name: cantera_env3
channels:
  - conda-forge
  - cantera
  - rmg
  - defaults
dependencies:
  - cantera=2.4.0=np115py37_2
  - numpy=1.15.4=py37h7e9f1db_0
  - pandas=0.25.1=py37he6710b0_0
  - scipy=1.3.1=py37h7c811a0_0
